# Generated by Django 5.1.5 on 2025-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csquestion',
            name='correct_answer',
            field=models.CharField(max_length=50),
        ),
    ]
