# Generated by Django 5.1.5 on 2025-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_csquestion_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='classic_images/'),
        ),
    ]
