# Generated by Django 5.1.5 on 2025-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_classicleaderboard_csleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='csleaderboard',
            name='difficulty',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
